### ISSUE TITLE
Error with LtExp, maybe. And new Tests for LtExp.

### ISSUE THREAD

**Issue by zFightx** [UnB-CIC/tp2-course#2]
Name: Alexandre Souza Costa Oliveira

I was reading the Expression.scala code and looking at LtExp's Eval method, I came across the following:

override def eval(): Value = {
    val l = lhs.eval()
    val r = rhs.eval()

    if(l.computeType() == TInt() && r.computeType() == TInt()) {
      **return new BoolValue(l.asInstanceOf[IntValue].value < r.asInstanceOf[IntValue].value)**
    }
     **return new BoolValue(l.asInstanceOf[IntValue].value < r.asInstanceOf[IntValue].value)**
  }

The method return is duplicated inside and outside the IF.
Not sure if it was purposeful, but I believe that when it is different variable types, there should be an exception warning that you could not compare the two types.

Example: false < 50, I think you should return an exception saying "can't compare Boolean to Integer"

To do this, I will submit a fix that throws an exception saying "can't compare two variables of different types".
In addition to more LtExp tests added to ExpressionTest.scala

That's it, thanks.

**Comment by rbonifacio** [comment]
Hi Alexandre. This is a bug. I think that we should only compare values of the same type. It does not make too much sense to compare an IntValue to a BooleanValue. If we try to evaluate something like `5 < True`, we definitely should throw an exception. Please, write some test cases, implement an interesting exception to deal with this kind of situation (perhaps TypeErrorException), and fix the code. 

Thanks.

**Comment by zFightx** [comment]
Hi. I submitted a fix #3 as well as new tests for the LtExp expression.

That's it, thanks.
